"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.deletePostAttachment = exports.getSavedPosts = exports.toggleSavePost = exports.aliasPostsByFollowing = exports.deletePost = exports.updatePost = exports.addNewPost = exports.getPost = exports.getAllPosts = exports.aliasMostPopular = void 0;
var aliasMostPopular_1 = require("./aliasMostPopular");
Object.defineProperty(exports, "aliasMostPopular", { enumerable: true, get: function () { return __importDefault(aliasMostPopular_1).default; } });
var getAllPosts_1 = require("./getAllPosts");
Object.defineProperty(exports, "getAllPosts", { enumerable: true, get: function () { return __importDefault(getAllPosts_1).default; } });
var getPost_1 = require("./getPost");
Object.defineProperty(exports, "getPost", { enumerable: true, get: function () { return __importDefault(getPost_1).default; } });
var addNewPost_1 = require("./addNewPost");
Object.defineProperty(exports, "addNewPost", { enumerable: true, get: function () { return __importDefault(addNewPost_1).default; } });
var updatePost_1 = require("./updatePost");
Object.defineProperty(exports, "updatePost", { enumerable: true, get: function () { return __importDefault(updatePost_1).default; } });
var deletePost_1 = require("./deletePost");
Object.defineProperty(exports, "deletePost", { enumerable: true, get: function () { return __importDefault(deletePost_1).default; } });
var aliasPostsByFollowing_1 = require("./aliasPostsByFollowing");
Object.defineProperty(exports, "aliasPostsByFollowing", { enumerable: true, get: function () { return __importDefault(aliasPostsByFollowing_1).default; } });
var toggleSavePost_1 = require("./toggleSavePost");
Object.defineProperty(exports, "toggleSavePost", { enumerable: true, get: function () { return __importDefault(toggleSavePost_1).default; } });
var getSavedPosts_1 = require("./getSavedPosts");
Object.defineProperty(exports, "getSavedPosts", { enumerable: true, get: function () { return __importDefault(getSavedPosts_1).default; } });
var deletePostAttachment_1 = require("./deletePostAttachment");
Object.defineProperty(exports, "deletePostAttachment", { enumerable: true, get: function () { return __importDefault(deletePostAttachment_1).default; } });
