"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const checkAuthenticated_1 = __importDefault(require("./checkAuthenticated"));
const confirmEmail_1 = __importDefault(require("./confirmEmail"));
const deleteMe_1 = __importDefault(require("./deleteMe"));
const logout_1 = __importDefault(require("./logout"));
const updateMe_1 = __importDefault(require("./updateMe"));
const updatePassword_1 = __importDefault(require("./updatePassword"));
const getUserById_1 = __importDefault(require("./getUserById"));
const toggleFollow_1 = __importDefault(require("./toggleFollow"));
const checkFollowing_1 = __importDefault(require("./checkFollowing"));
const getAllUsers_1 = __importDefault(require("./getAllUsers"));
const deleteMyPhoto_1 = __importDefault(require("./deleteMyPhoto"));
const router = (0, express_1.Router)();
router.use(getAllUsers_1.default);
router.use(checkAuthenticated_1.default);
router.use(confirmEmail_1.default);
router.use(deleteMe_1.default);
router.use(logout_1.default);
router.use(updateMe_1.default);
router.use(updatePassword_1.default);
router.use(getUserById_1.default);
router.use(toggleFollow_1.default);
router.use(checkFollowing_1.default);
router.use(deleteMyPhoto_1.default);
exports.default = router;
