"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SERVER_ERROR = exports.VALIDATION_ERROR = exports.NOT_FOUND = exports.FORBIDDEN = exports.UNAUTHORIZED = exports.BAD_REQUEST = exports.DELETED = exports.CREATED = exports.OK = void 0;
exports.OK = 200;
exports.CREATED = 201;
exports.DELETED = 204;
exports.BAD_REQUEST = 400;
exports.UNAUTHORIZED = 401;
exports.FORBIDDEN = 403;
exports.NOT_FOUND = 404;
exports.VALIDATION_ERROR = 422;
exports.SERVER_ERROR = 500;
